# Generated by Django 6.1 on 2026-09-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name="Matricule de l'élève"),
        ),
    ]
