# Generated by Django 6.1 on 2026-09-03 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulletin_type', models.CharField(choices=[('PERIOD', 'Bulletin de Période'), ('SEMESTER', 'Bulletin de Semestre'), ('ANNUAL', 'Bulletin Annuel')], default='PERIOD', max_length=20, verbose_name='Type de bulletin')),
                ('data_snapshot', models.JSONField(default=dict, verbose_name='Données figées du bulletin')),
                ('is_published', models.BooleanField(default=False, verbose_name='Proclamé / Validé')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de proclamation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_snapshots', to='academics.academicyear', verbose_name='Année scolaire')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_snapshots', to='academics.classroom', verbose_name='Classe')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletin_snapshots', to='assessments.period', verbose_name='Période (si applicable)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_snapshots', to='academics.student', verbose_name='Élève')),
            ],
        ),
    ]
