# Generated by Django 6.1 on 2026-09-03 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la période (ex: Première Période)')),
                ('order', models.PositiveIntegerField(verbose_name='Ordre (1, 2, 3...)')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Période clôturée')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='academics.academicyear', verbose_name='Année scolaire')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre / Description (ex: Interro 1 - Algèbre)')),
                ('evaluation_type', models.CharField(choices=[('INTERROGATION', 'Interrogation'), ('DEVOIR', 'Devoir'), ('TP', 'Travail Pratique'), ('EXAMEN', 'Examen')], default='INTERROGATION', max_length=30, verbose_name='Type')),
                ('max_score', models.FloatField(verbose_name='Maximum (ex: 10, 20)')),
                ('date_evaluated', models.DateField(verbose_name="Date de l'évaluation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academics.classroom', verbose_name='Classe')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academics.subject', verbose_name='Cours')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='teaching.teacher', verbose_name='Enseignant')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='assessments.period', verbose_name='Période')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='Note obtenue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='assessments.evaluation', verbose_name='Évaluation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.student', verbose_name='Élève')),
            ],
            options={
                'unique_together': {('student', 'evaluation')},
            },
        ),
    ]
