# Generated by Django 6.1 on 2026-09-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Code unique'),
        ),
    ]
