# Generated by Django 6.1 on 2026-09-03 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Notes / Biographie')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='accounts.userprofile', verbose_name='Profil Enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titular_teachers', to='academics.academicyear', verbose_name='Année scolaire')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titular_teacher', to='academics.classroom', verbose_name='Classe')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titular_classes', to='teaching.teacher', verbose_name='Enseignant Titulaire')),
            ],
            options={
                'unique_together': {('classroom', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.academicyear', verbose_name='Année scolaire')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.classroom', verbose_name='Classe')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject', verbose_name='Cours')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teaching.teacher', verbose_name='Enseignant')),
            ],
            options={
                'unique_together': {('teacher', 'subject', 'classroom', 'academic_year')},
            },
        ),
    ]
