# Generated by Django 6.1 on 2026-09-03 07:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='profile',
        ),
        migrations.AddField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Prénom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=10, verbose_name='Sexe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default='Inconnu', max_length=100, verbose_name='Nom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Matricule Professeur'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='schools.school', verbose_name='École'),
            preserve_default=False,
        ),
    ]
